* chicken-ffi-test-01 - A simple test of Chicken Scheme's FFI
This test simply compiles a Chicken module out of a C shared library made of a C header with a function that does nothing.

The purpose of this test is just to test whether the simplest of compilation and linking of C shared libraries works.
* Tested on
** Chicken 5.2.0 on amd64 Gentoo Linux
* License
Copyright (C) 2020  Sergey Goldgaber

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
